name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          python3 -m pip install --upgrade build
          cd lib
          python3 -m build
          cp -r dist/app_lib_py-0.0.0-py3-none-any.whl  "../dist/app_lib_py-${{github.ref_name}}-py3-none-any.whl"
          cp -r dist/app_lib_py-0.0.0.tar.gz  "../dist/app_lib_py-${{github.ref_name}}.tar.gz"
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
